<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//ES" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >

    <?php
    $titulo = "Listado Unidad de Medida";
    $labelDescripcion = "Descripci&oacuten de Unidad de Medida";
    $labelsGrillas = array('Descripci&oacuten de Unidad de Medida','ISO Unidad Medida');
    $apliGrillaJs = "/js/grillasmodulos/parametricos/gridUnidadMedida.js";
    $apliCss = "/css/cssmodulos/parametricos/unidadMedida.css";
    $apliCssGeneral = "/css/cssmodulos/CssGeneral.css";
    $apliJs = "/js/jsmodulos/parametricos/unidadmedida.js";
    //aqui tiene que ir lo mismo que va en unidadmedida.js
    $idCamposGrilla = array("id-registro","descripcionBusqueda-modal","isounidadmedida-modal");
    
    echo $this->headScript()->
            appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
            appendFile($this->baseUrl() . "/js/jquery-ui-1.8.17.custom.min.js")->
            appendFile($this->baseUrl() . '/js/i18n/grid.locale-es.js')->
            appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
            appendFile($this->baseUrl() . "/js/bootstrap.js")->
            appendFile($this->baseUrl() . $apliJs)->
            appendFile($this->baseUrl() . $apliGrillaJs)->
            appendFile($this->baseUrl() . "/js/jquery.tablescroll.js")->
            appendFile($this->baseUrl() . "/js/jquery.blockUI.js");

    echo $this->headLink()
            ->setIndent('  ')
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/generico.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.datepicker.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/jquery-ui-1.8.17.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/default.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/parametricos/menucss3/css/cool_nav.css")
            ->prependStylesheet($this->baseUrl() . $apliCss)
            ->prependStylesheet($this->baseUrl() . $apliCssGeneral)
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/contenedor.css");
    ?>

    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
	<title>Infocomedor</title>
        <body>
            <CENTER>

                <div class="modal hide fade in" id="modalEditar" >
                    <div class="modal-header">
                        <button data-dismiss="modal" class="close" type="button" id="cerrar-bot">X</button>
                        <div id="cabeceraModal" class="btn btn-info" >
                            <h3 id="editar-nuevo"></h3>
                        </div>

                        <div class="alert alert-block hide" id="warning-block-registro">
                            <div id="warning-message-registro"></div>
                        </div>
                        <div class="alert alert-success hide" id="success-block-registro">
                            Los datos han sido almacenados exitosamente
                        </div>
                        <div class="alert alert-error hide" id="error-block-modal">
                        </div>
                        <div class="alert alert-success hide" id="limpiar-block"></div>


                    </div>

                    <div class="modal-body">
                        <div id="contenedor-modal">
                            <table>
                                <!-- AGREGAR CAMPOS AQUI-->
                                <input type="hidden" id="<?php echo $idCamposGrilla[0]?>"></input>                                
                                <tr>
                                    <td><label for="<?php echo $idCamposGrilla[1]?>" id="<?php echo $idCamposGrilla[1].'-idioma'?>"><?php echo $labelsGrillas[0] ?><font style="color: red;">(*)</font></label></td>
                                    <td><input id="<?php echo $idCamposGrilla[1]?>" maxlength="50" style="width:150px;" onkeypress='return validarNumerosLetrasPorcentageEspacio(event);'></input></td>
                                </tr>
                                <tr>
                                    <td><label for="<?php echo $idCamposGrilla[2]?>" id="<?php echo $idCamposGrilla[2].'-idioma'?>"><?php echo $labelsGrillas[1] ?><font style="color: red;">(*)</font></label></td>
                                    <td><input id="<?php echo $idCamposGrilla[2]?>" maxlength="5" style="width:35px;" ></input></td>
                                </tr>
                            </table>
                        </div>
                        <div id="contenedor-modal">
                            <strong><font style="color: red;">(*)</font> Complete los campos marcados en el formulario para guardar el Registro</strong>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <a data-dismiss="modal" class="btn" href="#" id="cancelar-bot">Cancelar</a>
                        <a class="btn btn-info" id="guardar-registro" href="#">Guardar</a>
                    </div>
                </div>

                <div class="container-fluid">
                    <div class="row-fluid">
                        <div class="span10" id="span10">
                             <div  class="titulo-cabecera" style="text-align: left">
							<nav id="colorNav" >
			                    <ul>
			                        <li class="green">
			                            <a href="#" class="" title="MANTENIMIENTO">MANTENIMIENTO</a>
			                            <ul>
			                                <li><a href="/parametricos/empresa">EMPRESA</a></li>
			                                <li><a href="/parametricos/sucursal">SUCURSAL</a></li>
			                                <li><a href="/parametricos/estadopedido">ESTADO PEDIDO</a></li>
			                                <li><a href="/parametricos/concepto">CONCEPTO DE PAGOS</a></li>
			                                <li><a href="/parametricos/formapago">FORMAS DE PAGO</a></li>
			                                <li><a href="/parametricos/impuesto">IMPUESTOS</a></li>
			
			                            </ul>
			                        </li>
			                        <li class="red">
			                            <a href="#" class="" title="COMPRAS">COMPRAS</a>
			                            <ul>
			                                <li><a href="/compras/compra2">COMPRAS</a></li>
			                                <li><a href="/parametricos/proveedor">PROVEEDOR</a></li>
			                                <li><a href="#/compras/producto">PRODUCTO</a></li>
			                              
			                            </ul>
			                        </li>
			                        		<li class="blue">
										<a href="#" class="" title="VENTAS">VENTAS</a>
										<ul>
										 <li><a href="/parametricos/empresa">Empresa Clientes</a></li>
											 <li><a href="/parametricos/cliente">Clientes</a></li>
											 <li><a href="/ventas/karrito">Pedidos</a></li>
											 <li><a href="/ventas/factura">Facturacion</a></li>
											
										</ul>
									</li
			                        <li class="yellow">
			                            <a href="#" class="">PRODUCCION</a>
			                            <ul>
			                              </ul>
			                        </li>
			                        <li class="purple">
			                            <a href="#" class="">INFORMES</a>
			                            <ul>
			                            </ul>
			                        </li>
			                    </ul>
	                		</nav>  
	                </div> 
                                <div id="cabeceraFormulario" class="btn btn-info">
                                    <h1 id="cabecera-titulo" align="center">Unidad Medida</h1>

                                    <div class="alert alert-block hide" id="warning-block-registro-listado">
                                        <div id="warning-message-registro-listado"></div>
                                    </div>

                                    <div class="alert alert-success hide" id="success-block-registro-listado">
                                        <div id="success-message-registro-listado"></div>
                                    </div>

                                    <div class="alert alert-error hide" id="error-block-registro-listado">
                                    </div>

                                    <div class="alert alert-info hide" id="info-block-listado">
                                        <div id="info-message"></div>
                                    </div>



                                </div>
                                <div  id="clientes-div">
                                    <div id="contenedor">
                                        <fieldset>
                                            <table border="0">
                                                <tr>
                                                    <td><label for="descripcionBusqueda" id="descripcionBusqueda-idioma"><?php echo $labelDescripcion ?></label></td>
                                                    <td><input id="descripcionBusqueda" maxlength="50" onkeypress='return validarNumerosLetrasPorcentageEspacio(event);'></input></td>
                                                </tr>
                                            </table>
                                        </fieldset>

                                    </div>
                                </div>
                                <div  id="tab-content">
                                    <div id="contenedor" >
                                        <a id="buscarregistro"  class="btn btn-info"><img src="<?= $this->baseUrl() . "/css/images/buscar.png"; ?>" id="buscar-img" title="Buscar"  style="cursor: hand;"/></a>
                                        <a id="nuevoregistro"  class="btn btn-info"  data-toggle="modal"><img src="<?= $this->baseUrl() . "/css/images/nuevo.png"; ?>" id="nuevo-img" title="Nuevo"  style="cursor: hand;"/></a>
                                    </div> 
                                </div>
                                <div id="contenedor" >
                                    <fieldset>
                                        <table border="0">
                                            <tr>
                                                <td>
                                                    <div class="tab-content" id="tab-content">
                                                        <!-- DATOS DE IMPUESTOS --->
                                                        <div id="grillaPaginadorRegistro">
                                                            <table id="grillaRegistro"></table>
                                                            <div id="paginadorRegistro"></div>
                                                        </div>

                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                    </fieldset>
                                </div>

                        </div>	
                    </div>
                </div>
            </CENTER>
        </body>
    </html> 