<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//ES" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <?php
    echo $this->headScript()->
            appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
            appendFile($this->baseUrl() . "/js/jquery-ui-1.8.17.custom.min.js")->
            appendFile($this->baseUrl() . '/js/i18n/grid.locale-es.js')->
            appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
            appendFile($this->baseUrl() . "/js/bootstrap.js")->
            appendFile($this->baseUrl() . "/js/jsmodulos/compras/compra.js")->
            appendFile($this->baseUrl() . "/js/grillasmodulos/compras/gridCompra.js")->
            appendFile($this->baseUrl() . "/js/jquery.tablescroll.js")->
            appendFile($this->baseUrl() . "/js/jquery.blockUI.js");

    echo $this->headLink()
            ->setIndent('  ')
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/generico.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.datepicker.css")
            ->prependStylesheet($this->baseUrl() . "/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/jquery-ui-1.8.17.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap-responsive.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/compras/compra.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/default.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/contenedor.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/parametricos/menucss3/css/cool_nav.css");
    ?>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Infocomedor</title>
    </head>

    <body>

        <div class="container-fluid"> 
            <div class="row-fluid">
                <div class="span10">
                 <div  class="titulo-cabecera" style="text-align: left">
                    <nav id="colorNav" >
                        <ul>
                            <li class="menu">
                                <a href="<?php echo $this->baseUrl() ."/parametricos/menu";?>" class="">MENU</a>
                           </li>
                            <li class="red">
                                <a href="#" class="" title="COMPRAS">COMPRAS</a>
                                <ul>
                                    <li><a href="<?php echo $this->baseUrl() ."/parametricos/proveedor";?>">Proveedor</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/compras/compra2";?>">Compras - Pagos</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/compras/pagos";?>">Pagos</a></li>

                                </ul>
                            </li>
                            <li class="green">
                                <a href="#" class="" title="PRODUCCION">PRODUCCION</a>
                                <ul>
                                    <li><a href="<?php echo $this->baseUrl() ."/parametricos/tipoproducto";?>">Tipo Producto</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/parametricos/producto";?>">Producto</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/produccion/receta";?>">Recetas</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/produccion/productofinal";?>">Produccion</a></li>

                                </ul>
                            </li>
                            <li class="blue">
                                <a href="#" class="" title="VENTAS">VENTAS</a>
                                <ul>
                                     <li><a href="<?php echo $this->baseUrl() ."/parametricos/empresa";?>">Empresa Clientes</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/parametricos/cliente";?>">Clientes</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/ventas/karrito";?>">Pedidos</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/ventas/factura";?>">Facturacion</a></li>

                                </ul>
                            </li>
                            <li class="yellow">
                                <a href="#" class="" title="INVENTARIO">INVENTARIO</a>
                                <ul>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/inventario";?>">Inventario</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/ajusteinventario";?>">Ajuste</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/bajastock";?>">Baja Stock</a></li>
                                </ul>
                            </li>
                            <li class="purple">
                                <a href="#" class=""title="CAJA">CAJA</a>
                               <ul>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/caja";?>">Caja</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/tipomovimiento";?>">Tipo Movimiento</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/movcaja";?>">Movimientos</a></li>
                               </ul>
                           </li>
                           <li class="">
                                <a href="<?php echo $this->baseUrl() ."/menus/menu";?>">LogOut</a>
                           </li>

                        </ul>
                    </nav>
	         </div>        
            </div>
        </div>
    </body>
</html>