<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//ES" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <?php
    echo $this->headScript()->
            appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
            appendFile($this->baseUrl() . "/js/jquery-ui-1.8.17.custom.min.js")->
            appendFile($this->baseUrl() . '/js/i18n/grid.locale-es.js')->
            appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
            appendFile($this->baseUrl() . "/js/bootstrap.js")->
            appendFile($this->baseUrl() . "/js/jsmodulos/produccion/Inventario.js")->
            appendFile($this->baseUrl() . "/js/grillasmodulos/produccion/gridInventario.js")->
            appendFile($this->baseUrl() . "/js/jquery.tablescroll.js")->
            appendFile($this->baseUrl() . "/js/jquery.blockUI.js");

    echo $this->headLink()
            ->setIndent('  ')
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/generico.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.datepicker.css")
            ->prependStylesheet($this->baseUrl() . "/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/jquery-ui-1.8.17.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap-responsive.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/compras/compra.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/default.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/contenedor.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/parametricos/menucss3/css/cool_nav.css")
    ?>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Infocomedor</title>
    </head>
    <body>

        <div class="container-fluid"> 
            <div class="row-fluid">
                <div class="span10">
                 <div  class="titulo-cabecera" style="text-align: left">
                     <nav id="colorNav" >
                        <ul>
                            <li class="menu">
                                <a href="<?php echo $this->baseUrl() ."/parametricos/menu";?>" class="">MENU</a>
                           </li>
                            <li class="red">
                                <a href="#" class="" title="COMPRAS">COMPRAS</a>
                                <ul>
                                    <li><a href="<?php echo $this->baseUrl() ."/parametricos/proveedor";?>">Proveedor</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/compras/compra2";?>">Compras - Pagos</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/compras/pagos";?>">Pagos</a></li>

                                </ul>
                            </li>
                            <li class="green">
                                <a href="#" class="" title="PRODUCCION">PRODUCCION</a>
                                <ul>
                                    <li><a href="<?php echo $this->baseUrl() ."/parametricos/tipoproducto";?>">Tipo Producto</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/parametricos/producto";?>">Producto</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/produccion/receta";?>">Recetas</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/produccion/productofinal";?>">Produccion</a></li>

                                </ul>
                            </li>
                            <li class="blue">
                                <a href="#" class="" title="VENTAS">VENTAS</a>
                                <ul>
                                     <li><a href="<?php echo $this->baseUrl() ."/parametricos/empresa";?>">Empresa Clientes</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/parametricos/cliente";?>">Clientes</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/ventas/karrito";?>">Pedidos</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/ventas/factura";?>">Facturacion</a></li>

                                </ul>
                            </li>
                            <li class="yellow">
                                <a href="#" class="" title="INVENTARIO">INVENTARIO</a>
                                <ul>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/inventario";?>">Inventario</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/ajusteinventario";?>">Ajuste</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/bajastock";?>">Baja Stock</a></li>
                                </ul>
                            </li>
                            <li class="purple">
                                <a href="#" class=""title="CAJA">CAJA</a>
                               <ul>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/caja";?>">Caja</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/tipomovimiento";?>">Tipo Movimiento</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/movcaja";?>">Movimientos</a></li>
                               </ul>
                           </li>
                           <li class="">
                                <a href="<?php echo $this->baseUrl() ."/menus/menu";?>">LogOut</a>
                           </li>

                        </ul>
                    </nav>
	                </div> 
                    <div  class="titulo-cabecera">
                        <h1 id="cabecera-titulo">Inventario</h1>

                    </div>
                   
                    <div>
                        <div class="alert alert-block hide" id="warning-block">
                            <div id="warning-message"></div>
                        </div>
                        <div class="alert alert-success hide" id="success-block">
                            <div id="success-message"></div>
                        </div>
                        <div class="alert alert-info hide" id="info-block">
                            <div id="info-message"></div>
                        </div>
                        <div id="contenedor" class="filtro" align=right>
                            <table style="width: 90%; padding: 1%;">
                                <tr>
                                         <td style="width: 15%; text-align: right">
                                        Tipo de Producto
                                    </td>
                                    <td style="width: 35%">
                                        <input id="descripciontipoproducto-filtro"  maxlength="45" class="input-block-level" >
                                    </td>

                                    <td style="width: 15%; text-align: right">
                                        Producto
                                    </td>
                                    <td >
                                        <input id="descripcionproductofinal-filtro"  class="input-block-level" >
                                    </td>
                                    
                                  
                                </tr>
                            </table>
                        </div>
                        <div  id="tab-content">
                            <div id="contenedor" align=center>
                               
                                <a id="buscar-registro"  class="btn btn-info"><img src="<?= $this->baseUrl() . "/css/images/buscar.png"; ?>" id="buscar-img" title="Buscar"  style="cursor: hand;"/></a>
                                <a id="nuevo-registro"  class="btn btn-info" <?php echo $this->guardar ?>><img src="<?= $this->baseUrl() . "/css/images/nuevo.png"; ?>" id="nuevo-img" title="Nuevo"  style="cursor: hand;"/></a>
                                

                            </div> 
                        </div>
                    </div>
                    <div id="contenedor" >
                        <div class="contenedor-grid">
                            <table id="grillaRegistro"></table>
                            <div id="paginadorRegistro"></div>
                        </div>
                    </div>
                </div>


                <div class="modal hide" id="modalEditar">
                    <div class="modal-header">

                        <div id="cabeceraModal" class="btn btn-info">
                            <h3 id="editar-nuevo" style="color:white; display: inline;"></h3>
                            <button data-dismiss="modal" class="close" type="button" id="cerrar-bot" style="display: inline">X</button>
                        </div>
                        <div class="alert alert-block hide" id="warning-block-modal">
                            <div id="warning-message-modal"></div>
                        </div>
                        <div class="alert alert-error hide" id="error-block"></div>
                        <div class="alert alert-success hide" id="limpiar-block"></div>
                    </div>



                    <div class="modal-body">

                         <table id="addTipoProducto" class="table well form-inline">

                            <tr style="width:50%">
                            <td style="width:30%">
                                <label for="tipo-productos-modal" id="tipo-productos-modal-idioma">Descripcion Tipo producto</label>
                           </td >
                            <td style="width:20%" >
                                <select  name="tipo-productos-modal" id="tipo-productos-modal" 
                                class="input-block-level" onchange="buscarProductos(this.options[this.selectedIndex].value)">
                                    <option value="-1">Seleccione</option>
                               </select>
                                </td>
                            </tr>                              
                        </table> 
                        <!-- agregar productos-->
                        <input id="inventario-codigo" style="visibility: hidden;" >
                        <table id="addProductos" class=" table well form-inline">
                           
                            <!-- Valores de los items a ingresar-->
                            <tr id="detalle-receta">  
                                <td style="width:11%">
                                	<label for="codproducto-title" id="factura-title-idioma">Cod Producto</label>
                                    <div class="btn-confirmar" style="width: 80%">
                                        <input id="codproducto-item"  maxlength="10" class="input-block-level" onchange="" 
                                               style="width: 80%" placeholder="Ingresa el codigo" required>
                                        <button class="btn-compra" onclick="productvalidation('cod');"><img src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0007_Tick.png"; ?>"/></button>
                                    </div>
                                </td >
                                <td style="width: 20%">
                                <label for="descripcionproducto-title" id="factura-title-idioma">Descripci&oacuten</label>
                                    <div class="btn-confirmar" style="width: 90%">  
                                        <input id="descripcionproducto-item"  class="input-block-level" onchange="" style="width: 95%" placeholder="Escribi en nombre del producto" required>
                                        <button class="btn-compra" onclick="productvalidation('descripcion');"> <img  src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0007_Tick.png"; ?>" alt="Confirmar Código"/></button>
                                    </div> 
                                </td>
                                <td style="width: 3%">
                                <label for="unidadmedida-title" id="factura-title-idioma">Unidad Medida</label>
                                    <input id="codUnidadMedida-item" type="hidden" value="1">
                                    <input id="unidadmedida-item"  maxlength="10" class="input-block-level" onchange="">
                                    <input id="saldo-item"  maxlength="10" class="input-block-level" style="visibility: hidden;">
                                </td>
                                <td style="width: 4%">
                               		<br>
                                    <button class="btn-compra" type="button" id="addItem"><img src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0009_Add.png"; ?>"/></button>
                             		<button class="btn-compra" type="button" id="reloadItem"><img src="<?= $this->baseUrl() . "/css/Icons/thumbails/_Reload.png"; ?>"/></button>
                                </td>
                            </tr>

                        </table>

                    </div>
                    <div id="contenedormodal" style="width: 97%"> 
                        <div id="contenedor-grid" class="contenedor-grid">

                            <!--                            Aca se pone la grilla para el modal-->
                            <table id="grillaRegistroModal"></table>
                            <div id="paginadorRegistroModal"></div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a data-dismiss="modal" class="btn" id="cancelar-bot"><?php echo 'Cancelar'; ?></a>
                        <a class="btn btn-info" id="guardar"><?php echo 'Guardar'; ?></a>
                        <a class="btn btn-info" id="guardarinventario"><?php echo 'Cargar'; ?></a>
                    </div>
                </div>

            </div>
        </div>
    </body>
</html>