<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//ES" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <?php
    echo $this->headScript()->
            appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
            appendFile($this->baseUrl() . "/js/jquery-ui-1.8.17.custom.min.js")->
            appendFile($this->baseUrl() . '/js/i18n/grid.locale-es.js')->
            appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
            appendFile($this->baseUrl() . "/js/bootstrap.js")->
            appendFile($this->baseUrl() . "/js/jsmodulos/compras/Reportecompras.js")->
            appendFile($this->baseUrl() . "/js/jquery.tablescroll.js")->
            appendFile($this->baseUrl() . "/js/jquery.blockUI.js");

    echo $this->headLink()
            ->setIndent('  ')
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/generico.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.datepicker.css")
            ->prependStylesheet($this->baseUrl() . "/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/jquery-ui-1.8.17.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap-responsive.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/compras/compra.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/default.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/contenedor.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/parametricos/menucss3/css/cool_nav.css");
    ?>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Infocomedor</title>
    </head>

    <body>

        <div class="container-fluid"> 
            <div class="row-fluid">
                <div class="span10">
                 <div  class="titulo-cabecera" style="text-align: left">
                    <nav id="colorNav" >
                        <ul>
                            <li class="menu">
                                <a href="<?php echo $this->baseUrl() ."/parametricos/menu";?>" class="">MENU</a>
                           </li>
                            <li class="red">
                                <a href="#" class="" title="COMPRAS">COMPRAS</a>
                                <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/proveedor";?>">Proveedor</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/compra2";?>">Compras - Pagos</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/pagos";?>">Pagos</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/Reportecompras";?>">Reporte Compras</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/Reportepagos";?>">Reporte Pagos</a></li>

                              
                            </ul>
                            </li>
                            <li class="green">
                                <a href="#" class="" title="PRODUCCION">PRODUCCION</a>
                                <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/tipoproducto";?>">Tipo Producto</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/producto";?>">Producto</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/produccion/receta";?>">Recetas</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/produccion/productofinal";?>">Produccion</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/produccion/Reporteproduccion";?>"> Reporte Produccion</a></li>

                            </ul>
                            </li>
                            <li class="blue">
                                <a href="#" class="" title="VENTAS">VENTAS</a>
                                <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/empresa";?>">Empresa Clientes</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/parametricos/cliente";?>">Clientes</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/karrito";?>">Pedidos</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/factura";?>">Facturación</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/Reporteclientes";?>">Reporte Clientes</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/Reportefacturacion";?>">Reporte Facturación</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/Reportepedidos";?>">Reporte Pedidos</a></li>
                                
                            </ul>
                            </li>
                            <li class="yellow">
                                <a href="#" class="" title="INVENTARIO">INVENTARIO</a>
                                <ul>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/inventario";?>">Inventario</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/ajusteinventario";?>">Ajuste</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/bajastock";?>">Baja Stock</a></li>
                                </ul>
                            </li>
                            <li class="purple">
                                <a href="#" class=""title="CAJA">CAJA</a>
                               <ul>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/caja";?>">Caja</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/tipomovimiento";?>">Tipo Movimiento</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/movcaja";?>">Movimientos</a></li>
                                   <li><a href="<?php echo $this->baseUrl() ."/caja/Reportearqueocaja";?>">Reporte Arqueo de caja</a></li>
                                </ul>
                           </li>
                           <li class="">
                                <a href="<?php echo $this->baseUrl() ."/menus/menu";?>">LogOut</a>
                           </li>

                        </ul>
                    </nav>

	         </div> 
                    <div  class="titulo-cabecera">
                        <h1 id="cabecera-titulo">Compras</h1>

                    </div>
                  
                    <div>
                        <div class="alert alert-block hide" id="warning-block-title">
                            <div id="warning-message-title"></div>
                        </div>
                        <div class="alert alert-success hide" id="success-block-title">
                            <div id="success-message-title"></div>
                        </div>
                        <div class="alert alert-info hide" id="info-block-listado">
                            <div id="info-message"></div>
                        </div>
                        <div id="contenedor" class="filtro" align=center>
                            <table style="width: 90%; padding: 1%;">
                                <tr>
                                    <td style="width: 10%;">
                                        <label for="codproveedor-filtro" id="codproveedor-filtro-idioma">C&oacute;digo Proveedor</label>
                                    </td>
                                    <td style="width: 10%">
                                        <input id="codproveedor-filtro"  class="input-block-level just-number" >
                                    </td>
                                    <td style="width: 7%">
                                        <label for="nameproveedor-filtro" id="nameproveedor-filtro-idioma">Proveedor</label>
                                    </td>
                                    <td style="width: 13%">
                                        <input id="nameproveedor-filtro"  class="input-block-level" >
                                    </td>
                                    <td style="width: 7%">
                                        <label for="codigointerno-filtro" id="codigointerno-filtro-idioma">C&oacute;d. Interno</label>
                                    </td>
                                    <td style="width: 13%">
                                        <input id="codigointerno-filtro"  maxlength="10" class="input-block-level" >
                                    </td>
                                    <td style="width: 10%">
                                        <label for="controlfiscal-filtro" id="controlfiscal-filtro-idioma">Control Fiscal</label>
                                    </td>
                                    <td style="width: 40%">
                                        <input id="controlfiscal-filtro_1"  class="input-block-level" maxlength="3" value="001" style="width: 10%; display: inline; " >
                                        <input id="controlfiscal-filtro_2"  maxlength="3" class="input-block-level" max="3" value="001" style="width: 10%; display: inline;" >
                                        <input id="controlfiscal-filtro_3"  maxlength="10" class="input-block-level just-number" style="width: 30%; display: inline;" >
                                    </td>
                                </tr>
                            </table>
                            <table style="width: 90%; padding: 1%;">
                                <tr>
                                    <td style="width: 10%">
                                        <label for="fechaemision-filtro" id="fechaemision-filtro-idioma">Emision</label>
                                    </td>
                                    <td style="width: 15%">
                                        <input id="fechaemision-filtro"  class="input-block-level">
                                    </td>
                                    <td style="width: 10%">
                                        <label for="fechavencimiento-filtro" id="fechavencimiento-filtro-idioma">Vencimiento</label>
                                    </td>
                                    <td style="width: 15%">
                                        <input id="fechavencimiento-filtro"  class="input-block-level" >
                                    </td>
                                    <td style="width: 10%">
                                        <label for="formapago-filtro" id="formapago-filtro-idioma">Pago</label>
                                    </td>
                                    <td style="width: 15%">
                                        <select class="input-block-level" name="formapago-filtro-idioma" id="formapago-filtro" onchange="">
                                            <option value="-1">Seleccione</option>
                                            <option value="1">Contado</option>
                                            <option value="2">Cr&eacute;dito</option>
                                        </select>
                                    </td>

                                </tr>
                            </table>
                        </div>
                        <div  id="tab-content">
                            <div id="contenedor" align=center>
<!--                                <a id="backmenu"  class="btn btn-info" href="/parametricos/menu"><img src="<?= $this->baseUrl() . "/css/images/home.png"; ?>"  title="VOLVER AL MENU"/></a>-->
                                <a id="imprimirReporte"  class="btn btn-info"><img src="<?php echo $this->baseUrl() . "/css/images/buscar.png"; ?>" id="buscar-img" title="Genera Reporte de Compras"  style="cursor: hand;"/></a>                             
                            </div> 
                        </div>
                    </div>
                    <div id="contenedor" >
                        <div class="contenedor-grid">
                            <table id="grillaCompras"></table>
                            <div id="paginadorCompras"></div>
                        </div>
                    </div>
                </div>


                <div class="modal hide" id="modalEditar">
                    <div class="modal-header">

                        <div id="cabeceraModal" class="btn btn-info">
                            <h3 id="editar-nuevo" style="color:white; display: inline;"><?php echo 'EditarGestionComisionVendedores'; ?></h3>
                            <button data-dismiss="modal" class="close" type="button" id="cerrar-bot" style="display: inline">x</button>
                        </div>
                        <div class="alert alert-block hide" id="warning-block">
                            <div id="warning-message"></div>
                        </div>
                        <div class="alert alert-success hide" id="success-block"><?php echo 'datosalmacenadosexitosamente'; ?></div>
                        <div class="alert alert-error hide" id="error-block"></div>
                        <div class="alert alert-success hide" id="limpiar-block"></div>
                    </div>
                    <!-- NUEVO - EDITAR --->
                    <div class="modal-body">

                        <input class="input-block-level" type="hidden" id="id-compra">
                        <input class="input-block-level" type="hidden" id="estado-compra">
                        <!-- datos del proveedor-->
                        <table class="well form-inline"> 
                            <tr>    
                                <td style="width: 10%">
                                    <label for="codigoproveedor-modal" id="codigoproveedor-modal-idioma">C&oacute;digo</label>
                                </td>
                                <td>
                                    <button class="btn-compra" type="button" onclick="validaProveedor('cod');"><img src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0007_Tick.png"; ?>"/></button>
                                </td>
                                <td style="width: 10%">
                                    <input id="codigoproveedor-modal"  maxlength="10" class="input-block-level just-number" 
                                           onchange=""  >
                                </td>

                                <td style="width: 10%">
                                    <label for="ruc-modal" id="proveedorRuc-modal-idioma">RUC</label>
                                </td>
                                <td>
                                    <button class="btn-compra" type="button" onclick="validaProveedor('ruc');"><img src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0007_Tick.png"; ?>"/></button>
                                </td>
                                <td style="width: 15%">
                                    <input id="ruc-modal"  maxlength="10" class="input-block-level" onchange=""  >
                                </td>

                                <td style="width: 15%">
                                    <label for="razonsocial-modal" id="razonsocial-modal-idioma">Raz&oacute;n Social</label>
                                </td>
                                <td>
                                    <button class="btn-compra" type="button" onclick="validaProveedor('name');"><img src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0007_Tick.png"; ?>"/></button>
                                </td>
                                <td style="width: 40%">
                                    <input  type="hidden" id="idproveedor" value="1">
                                    <input id="razonsocial-modal"  type="text" class="input-block-level"  >
                                </td>
                                <td>
									<button id="reloadProveedor" type="button" class="btn-compra" title="Reload Product"><img src="/css/Icons/thumbails/_Reload.png"></button>
								</td>
                            </tr>
                        </table>

                        <br>
                        <!-- datos de la factura-->
                        <table class="well form-inline">
                            <tr>
                                <td id="numeroFacturaLb" style="width: 6%">
                                    <label for="factura-modal" id="factura-modal-idioma">N&uacute;mero Factura</label>
                                </td>
                                <td id="numeroFacturaIn"style="width: 10%">
                                    <input id="factura-modal"  maxlength="10" class="input-block-level just-number" onchange=""  >
                                </td>
                                </td>
                                <td style="width: 5%">
                                    <label for="controlfiscal-modal" id="controlfiscal-modal-idioma">Control Fiscal</label>
                                </td>
                                <td style="width: 15%">
                                    <input id="controlfiscal-modal_1"  class="input-block-level" maxlength="3" value="001" style="width: 20%" >
                                    <input id="controlfiscal-modal_2"  maxlength="10" class="input-block-level" max="3" value="001" style="width: 20%" >
                                    <input id="controlfiscal-modal_3"  maxlength="10" class="input-block-level just-number" style="width: 50%" >

                                </td>
                                <td style="width: 10%" class="hide">
                                    <input type="radio" name=formaPago value="1" checked>Contado

                                    <input type="radio" name=formaPago value="2" >Cr&eacute;dito


                                </td>

                                <td style="width: 6%"> 
                                    <label for="FechaFactura-modal" id="FechaFactura-modal-idioma">Fechas Factura</label>
                                </td>
                                <td style="width: 10%">
                                    <input id="FechaFactura-modal"  maxlength="10" class="input-block-level" onchange="" >
                                </td>
                                <td style="width: 6%">
                                    <label for="FechaVencimiento-modal" id="FechaVencimiento-modal-idioma">Fecha Vencimiento</label>
                                </td>
                                <td style="width: 10%">
                                    <input id="FechaVencimiento-modal"  maxlength="10" class="input-block-level" onchange="" >
                                </td>
                            </tr>

                        </table>

                        <br>

                        <!-- agregar productos-->
                        <table id="addProductos" class="table-bordered table well form-inline">
                            <!-- Titulos de los items a ingresar-->
                            <tr>
                                <td >
                                    <label for="codproducto-title" id="factura-title-idioma">C&oacute;d Producto</label>
                                </td>
                                <td >
                                    <label for="descripcionproducto-title" id="factura-title-idioma">Descripci&oacute;n</label>
                                </td>
                                <td >
                                    <label for="cantidad-title" id="factura-title-idioma">Cantidad</label>
                                </td>
                                <td >
                                    <label for="unidadmedida-title" id="factura-title-idioma">Unidad Medida</label>
                                </td>
                                <td >
                                    <label for="precionunitario-title" id="factura-title-idioma">Precio Unitario</label>
                                </td>
                                <td >
                                    <label for="tipoimpuesto-title" id="factura-title-idioma">Tipo Impuesto</label>
                                </td>
                                <td >
                                    <label for="totalpacial-title" id="factura-title-idioma">Total Parcial</label>
                                </td>
                            </tr>
                            <!-- Valores de los items a ingresar-->
                            <tr>
                                <td style="width:11%">
                                    <div class="btn-confirmar" style="width: 80%">
                                        <input id="codproducto-item"  maxlength="10" class="input-block-level just-number" onchange="" 
                                               style="width: 80%" >
                                        <button class="btn-compra" onclick="productvalidation('cod');"><img src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0007_Tick.png"; ?>"/></button>
                                    </div>
                                </td >
                                <td style="width: 22%">
                                    <div class="btn-confirmar" style="width: 90%">  
                                        <input id="descripcionproducto-item"  class="input-block-level" onchange="" style="width: 95%" equired>
                                        <button class="btn-compra" onclick="productvalidation('descripcion');"> <img  src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0007_Tick.png"; ?>" alt="Confirmar Codigo"/></button>
                                    </div> 
                                </td>
                                <td style="width: 5%; text-align: center;">
                                    <input id="cantidad-item"  maxlength="10" class="input-block-level just-number" onchange="calculoTotalParcial();" value="0.000" type="number" step="0.1" >
                                </td>
                                <td style="width: 3%">
                                    <input id="codUnidadMedida-item" type="hidden" value="1">
                                    <input id="unidadmedida-item"  maxlength="10" class="input-block-level" onchange="">
                                </td>
                                <td style="width: 6%; text-align: right;" >
                                    <input id="preciounitario-item"  maxlength="10" class="input-block-level just-number" onchange="calculoTotalParcial();" value="0.000" type="number" step="0.1">
                                </td>
                                <td style="width: 4%">
                                    <select class="input-block-level" name="tipoimpuesto-item" id="tipoimpuesto-item" onchange="">
                                        <option value="-1">Seleccione</option>
                                        <option value="5">5%</option>
                                        <option value="10">10%</option>
                                    </select>
                                <!--<input id="tipoimpuesto-item"  maxlength="10" class="input-block-level" onchange="">-->
                                </td>
                                <td style="width: 9%; text-align: right;" >
                                    <input id="totalparcial-item"  maxlength="10" class="input-block-level" onchange="">
                                </td>
                                <td style="width: 5%">
                                    <button class="btn-compra" type="button" id="addItem"><img src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0009_Add.png"; ?>"/></button>
                                	<button title="Reload Product" class="btn-compra" type="button" id="reloadProducto"><img src="/css/Icons/thumbails/_Reload.png"></button>
                                </td>
                            </tr>

                        </table>

                    </div>
                    <div id="contenedormodal" > 
                        <div id="contenedor-grid" class="contenedor-grid">

                            <!--                            Aca se pone la grilla para el modal-->
                            <table id="grillaComprasModal"></table>
                            <div id="paginadorComprasModal"></div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a data-dismiss="modal" class="btn" id="cancelar-bot"><?php echo 'Cancelar'; ?></a>
                        <a class="btn btn-info" id="guardar"><?php echo 'Guardar'; ?></a>
                    </div>
                </div>

                <!--    MODAL PAGOS     -->
                <div class="modal hide" id="modalPagos">
                    <div class="modal-header">
                        <div id="cabeceraModal" class="btn btn-info">
                            <h3 id="editar-nuevo" style="color:white; display: inline;"><?php echo 'Realizar Pagos'; ?></h3>
                            <button data-dismiss="modal" class="close" type="button" id="cerrar-bot-pagos" style="display: inline">x</button>
                        </div>
                        <div class="alert alert-block hide" id="warning-block-pagos">
                            <div id="warning-message-pagos"></div>
                        </div>
                        <div class="alert alert-success hide" id="success-block-pagos"><?php echo 'datosalmacenadosexitosamente'; ?></div>
                        <div class="alert alert-error hide" id="error-block-pagos"></div>
                        <div class="alert alert-success hide" id="limpiar-block"></div>
                    </div>
                    

                    <div class="modal-body">

                        <input class="input-block-level" type="hidden" id="id-compra">
                        <!-- datos del proveedor-->
                        <table class="well form-inline"> 
                            <tr>    
                                <td style="width: 10%">
                                    <label for="codigoproveedor-modal-pagos" id="codigoproveedor-modal-pagos-idioma">C&oacute;digo</label>
                                </td>
                                <td>
                                    <button class="btn-compra" type="button" onclick="validaProveedor('cod');"><img src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0007_Tick.png"; ?>"/></button>
                                </td>
                                <td style="width: 10%">
                                    <input id="codigoproveedor-modal-pagos"  maxlength="10" class="input-block-level just-number" 
                                           onchange=""  >
                                </td>

                                <td style="width: 10%">
                                    <label for="ruc-modal-pagos" id="proveedorRuc-modal-pagos-idioma">Ruc</label>
                                </td>
                                <td>
                                    <button class="btn-compra" type="button" onclick="validaProveedor('ruc');"><img src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0007_Tick.png"; ?>"/></button>
                                </td>
                                <td style="width: 15%">
                                    <input id="ruc-modal-pagos"  maxlength="10" class="input-block-level" onchange="" >
                                </td>

                                <td style="width: 15%">
                                    <label for="razonsocial-modal-pagos" id="razonsocial-modal-pagos-idioma">Raz&oacute;n Social</label>
                                </td>
                                <td>
                                    <button class="btn-compra" type="button" onclick="validaProveedor('name');"><img src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0007_Tick.png"; ?>"/></button>
                                </td>
                                <td style="width: 40%">
                                    <input  type="hidden" id="idproveedor-pagos" value="1">
                                    <input id="razonsocial-modal-pagos"  type="text" class="input-block-level" >
                                </td>


                            </tr>
                        </table>
                        <br>
                        <br>
                        <table class="well form-inline">
                            <tr>
                                <input id="codigoCaja-modal-pagos" style="visibility: hidden">
                                <input id="usuarioCaja-modal-pagos" style="visibility: hidden">
                                <td id="numeroFactura-pago" style="width: 6%">
                                    <label for="factura-modal-pagos" id="factura-modal-pagos-idioma">N&uacute;mero Factura</label>
                                </td>
                                <td id="numeroFacturaIn-pagos"style="width: 10%">
                                    <input id="factura-modal-pagos"  maxlength="10" class="input-block-level just-number" onchange=""  >
                                </td>
                                </td>
                                <td style="width: 10%">
                                    <label for="controlfiscal-modal-pagos" id="controlfiscal-modal-pagos-idioma">Control Fiscal</label>
                                </td>
                                <td style="width: 20%">
                                    <input id="controlfiscal-modal_1-pagos"  class="input-block-level" maxlength="3" value="001" style="width: 20%" >
                                    <input id="controlfiscal-modal_2-pagos"  maxlength="10" class="input-block-level" max="3" value="001" style="width: 20%" >
                                    <input id="controlfiscal-modal_3-pagos just-number"  maxlength="10" class="input-block-level" style="width: 50%"  >

                                </td>
                                <td style="width: 5%">
                                    <label for="montoTotal-pagos" id="montoTotal-modal-pagos-idioma">Monto</label>
                                </td>
                                <td style="width: 10%">
                                    <input id="montoTotal-pagos"  class="input-block-level just-number">
                                    <input id="codigoMoneda-pagos" type="hidden" >
                                </td>
                                <td style="width: 5%">
                                    <label for="pagosrealizados-modal-pagos" id="pagosrealizados-modal-pagos-idioma">Pagos</label>
                                </td>
                                <td style="width: 10%">
                                    <input id="pagosrealizados-modal-pagos"  class="input-block-level just-number" maxlength="3">
                                </td>
                                <td style="width: 5%">
                                    <label for="saldoPendiente-modal-pagos" id="saldoPendiente-modal-pagos-idioma">Saldo</label>
                                </td>
                                <td style="width: 10%">
                                    <input id="saldoPendiente-modal-pagos"  class="input-block-level just-number" maxlength="3">
                                </td>
                            </tr>

                        </table>

                        <table id="AgregarPagos" class="table well">
                            <tr>
                                <td style="text-align: right" class="checkboxes" >
                                    Efectivo : <input type="checkbox" name="formaPagoEfectivo" id="formaPagoEfectivo" checked value="EF" onclick="selectFormaPago('efectivo');">
                                    <br>
                                    Cheque : <input type="checkbox" name="formaPagoCheque" id="formaPagoCheque" value="CH" onclick="selectFormaPago('cheque');" >
                                     <br>
                                    Egreso : <input type="checkbox" name="formaPagoEgreso" id="formaPagoEgreso" value="EG"  onclick="selectFormaPago('egreso');" >
                                </td>
                                <td class="cheque">
                                    <label for="banco-modal-pagos" id="banco-modal-pagos-idioma">Banco:</label>
                                </td>
                                <td class="cheque">
                                    <input id="banco-modal-pagos"  class="input-block-level" onchange="" >
                                </td>
                                <td class="cheque">
                                    <label for="cheque-modal-pagos" id="cheque-modal-pagos-idioma">Cheque:</label>
                                </td>
                                 <td class="cheque">
                                    <input id="cheque-modal-pagos"  class="input-block-level just-number" onchange="" >
                                </td>
                                <td>
                                    <label for="montoPago-modal-pagos" id="montoPago-modal-pagos-idioma">Monto pago:</label>
                                </td>
                                <td >
                                    <input id="montoPago-modal-pagos"  class="input-block-level just-number" onchange="" >
                                </td>
                                <td>
                                    <label for="vuelto-modal-pagos" id="vuelto-modal-pagos-idioma">Vuelto:</label>
                                </td>
                                <td >
                                    <input id="vuelto-modal-pagos"  class="input-block-level" onchange="" >
                                    <input id="idEgreso-modal-pagos"  class="input-block-level just-number" style="visibility: hidden" >
                                </td>
                                <td>
                                    <button class="btn" type="button" id="addPagos"><img src="<?= $this->baseUrl() . "/css/Icons/thumbails/_0009_Add.png"; ?>"/></button>
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div id="contenedormodal" > 
                        <div id="contenedor-grid" class="contenedor-grid">
                            <!--                            Aca se pone la grilla para el modal-->
                            <table id="grillaComprasModalPagos"></table>
                            <div id="paginadorComprasModalPagos"></div>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <a data-dismiss="modal" class="btn" id="cancelar-bot-pagos"><?php echo 'Cancelar'; ?></a>
                        <a class="btn btn-info" id="guardar-pagos"><?php echo 'Guardar'; ?></a>
                    </div>
                </div>
                <!--    FIN - MODAL PAGOS     -->
                <div class="modal hide span7 offset2" id="modalBuscarEgreso">
                    <div class="modal-header">
                        <div id="cabeceraModal" class="btn btn-info">
                            <h3 id="editar-nuevo" style="color:white; display: inline;">Buscar Egreso</h3>
                            <button data-dismiss="modal" class="close" type="button" id="cerrar-bot-modal-egreso" style="display: inline">x</button>
                        </div>
                        <div class="alert alert-block hide" id="warning-block-modal-egreso">
                            <div id="warning-message-modal-egreso"></div>
                        </div>                        
                    </div>
                    <div id="contenedormodal" >
                        <table class=" form-inline">

                            <tr >
                            <td>
                                <label for="descripciontipomovimiento-modal" id="descripciontipomovimiento-modal-idioma">Descripcion Tipo Movimiento</label>
                            </td> 
                            <td>
                                <select  name="descripciontipomovimiento-modal" id="descripciontipomovimiento-modal" 
                                class="input-block-level" onchange="buscarEgreso(this.options[this.selectedIndex].value)">
                                    <option value="-1">Seleccione</option>
                               </select>
                            </td>
                            </tr>                              
                        </table> 
                        <div id="contenedor-grid" class="contenedor-grid">
                            <table id="grillaModalEgreso"></table>
                            <div id="paginadorModalEgreso"></div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <a data-dismiss="modal" class="btn" id="cancelar-bot-modal-egreso"><?php echo 'Cancelar'; ?></a>
                        <a class="btn btn-info" id="seleccionar-egreso"><?php echo 'Seleccionar'; ?></a>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>