<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//ES" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >

    <?php
    $apliCss = "/css/cssgenerico/default.css";
    $apliJs = "/js/jsmodulos/menus/menu.js";    
    
    echo $this->headScript()->
            appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
            appendFile($this->baseUrl() . "/js/jquery-ui-1.8.17.custom.min.js")->
            appendFile($this->baseUrl() . '/js/i18n/grid.locale-es.js')->
            appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
            appendFile($this->baseUrl() . "/js/bootstrap.js")->
            appendFile($this->baseUrl() . $apliJs)->
            appendFile($this->baseUrl() . "/js/jquery.tablescroll.js")->
            //appendFile($this->baseUrl() . "/js/jquery-1.4.2.min.js")->
            //appendFile($this->baseUrl() . "/js/jquery.validate.js")->
            appendFile($this->baseUrl() . "/js/jquery.blockUI.js");

    echo $this->headLink()
            ->setIndent('  ')
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.datepicker.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/jquery-ui-1.8.17.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . $apliCss)
            ->prependStylesheet($this->baseUrl() . "/css/login-box.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/contenedor.css");
    ?>

    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">
        <body background="<?php echo $this->baseUrl();?>/css/images/back_body_administrativo.jpg">
        <!--<div style="padding: 10px 0 0 250px;"><img src="images/mano.jpg" width="500" height="130" style="margin-left:90px;"/></div>
            -->
            <div style="padding: 100px 0 0 250px;">
                <div id="login-box">
                    <br />
                    <h3>Infocomedor</h3>
                    <br />
                    <h2>Login</h2>
                    <br />

                    <!-- <form style="border: #0A246A;" method="post" id="signin"> -->

                        <div id="login-box-name">Usuario:</div>                    
                        <div id="login-box-field">
                            <input id="username" name="username" type="usuario" class="form-login" title="Usuario" value="" size="30" maxlength="2048" onblur="passFocus();"/>
                        </div>
                        <div id="login-box-name">Password:</div><div id="login-box-field">
                            <input id="password" name="password" type="password" class="form-login" title="Password" value="" size="30" maxlength="2048" onblur="agenciaFocus();"/>
                        </div>
<!--                        
                        <div id="login-box-name">
                              Inmobiliaria</div>
                        
                            <div id="login-box-field">
                            <select name="SelecAgencia" id="SelecAgencia" class="form-login">
                                <option style="size: 30px" value="0">Seleccione Inmobiliria</option>
                            </select>
                        </div>
-->                      
                        <br />
                      <!--  <span  class="login-box-options">
                            <input type="checkbox" name="1" value="1"/> Remember Me <a href="#" style="margin-left:30px;">Forgot password?</a></span>
                      -->
                        <br />
                        <input id="signin_submit" class="login-btn" tabindex="6" type="image" src="<?php echo $this->baseUrl();?>/css/images/login-btn.png"/>
                    <!-- </form> -->
                </div>
            </div>

        </body>
    </html>