<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//ES" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >

    <?php
    $titulo = "Listado de Compras";
    $apliGrillaJs = "/js/grillasmodulos/compras/gridCompra.js";
    $apliCss = "/css/cssmodulos/compras/compra.css";
    $apliJs = "/js/jsmodulos/compras/Compra.js";
    $idCamposModal = array("id-registro","comboProveedorModal","nroFacturaCompraModal",
                    "fechaEmisionModal","fechaVencimientoModal","creditoModal","comboFormaPagoModal",
                    "comboInsumoModal","montoCompraModal","cantidadCompraModal","unidadMedidaInsumoModal","impuestoInsumoModal");
    $idCamposTitleModal = array("Proveedor","Nro. Factura","Fecha Emision","Fecha Vencimiento","Credito(S/N)","Forma Pago",
                            "Insumo","Monto Compra","Cantidad Compra","Unidad Medida Insumo");
    $idCamposBusqueda = array("comboSucursalBusqueda","comboProveedorBusuqueda","nroFacturaCompra");
    $idCamposTitleBusqueda = array("Sucursal","Proveedor","Nro. Factura");

    echo $this->headScript()->
            appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
            appendFile($this->baseUrl() . "/js/jquery-ui-1.8.17.custom.min.js")->
            appendFile($this->baseUrl() . '/js/i18n/grid.locale-es.js')->
            appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
            appendFile($this->baseUrl() . "/js/bootstrap.js")->
            appendFile($this->baseUrl() . $apliJs)->
            appendFile($this->baseUrl() . $apliGrillaJs)->
            appendFile($this->baseUrl() . "/js/jquery.tablescroll.js")->
            appendFile($this->baseUrl() . "/js/jquery.blockUI.js");

    echo $this->headLink()
            ->setIndent('  ')
            ->prependStylesheet($this->baseUrl() . "/css/ui.datepicker.css")
            ->prependStylesheet($this->baseUrl() . "/css/bootstrap.css")
            ->prependStylesheet($this->baseUrl() . "/css/jquery-ui-1.8.17.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/bootstrap.css")
            ->prependStylesheet($this->baseUrl() . "/css/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . $apliCss)
            ->prependStylesheet($this->baseUrl() . "/css/contenedor.css");
    ?>

    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es" lang="es">

        <body>
            <CENTER>
                <input type="hidden" id="baseUrl" name="baseUrl" value="<?= $this->baseUrl(); ?>">
                <!--MODAL DE ALTA O MODIFICACION DE REGISTRO-->
                <div class="modal hide fade in" id="modalEditar">
                    <div class="modal-header">
                        <button data-dismiss="modal" class="close" type="button" id="cerrar-bot">X</button>
                        <div id="cabeceraModal" class="btn btn-info" >
                            <h3 id="editar-nuevo"></h3>
                        </div>

                        <div class="alert alert-block hide" id="warning-block-registro">
                            <div id="warning-message-registro"></div>
                        </div>
                        <div class="alert alert-success hide" id="success-block-registro">
                            Los datos han sido almacenados exitosamente
                        </div>
                        <div class="alert alert-error hide" id="error-block-modal">
                        </div>
                        <div class="alert alert-success hide" id="limpiar-block"></div>


                    </div>
                                        
                    <div class="modal-body">
<!-- 
######################################   CAMPOS DE LA CABECERA   ######################################################################################
-->
                        <div id="contenedor-modal" >                        
                            <div id="cabeceraModal-idioma" class="btn btn-info" >
                                <h3 id="cabeceraModal-nuevo">Cabecera</h3>
                            </div><br><br>
                            <table>
                                <input type="hidden" id="<?php echo $idCamposModal[0]?>"></input>
                                <tr>
                                    <td><label for="<?php echo $idCamposModal[1]?>" id="<?php echo $idCamposModal[1]?>-idioma"><?php echo $idCamposTitleModal[0]?></label></td>
                                    <td><select class="input-small" name="<?php echo $idCamposModal[1]?>" id="<?php echo $idCamposModal[1]?>" style="width:150px;" ><option value="-1">---Seleccione---</option></select></td>

                                    <td><label for="<?php echo $idCamposModal[2]?>" id="<?php echo $idCamposModal[2]?>-idioma"><?php echo $idCamposTitleModal[1]?></label></td>
                                    <td><input id="<?php echo $idCamposModal[2]?>" maxlength="50"  onkeypress='return validarNumerosLetrasPorcentageEspacio(event);'></input></td>                                

                                    <td><label for="<?php echo $idCamposModal[3]?>" id="<?php echo $idCamposModal[3]?>-idioma" style="font-weight:bold"><?php echo $idCamposTitleModal[2]?></label></dt>
                                    <td><?php echo Application_View_Helper_Date::dateHelper($idCamposModal[3]); ?></td>

                                    <td><label for="<?php echo $idCamposModal[4]?>" id="<?php echo $idCamposModal[4]?>-idioma" style="font-weight:bold"><?php echo $idCamposTitleModal[3]?></label></dt>
                                    <td><?php echo Application_View_Helper_Date::dateHelper($idCamposModal[4]); ?></td>
                                    
                                    <td><label for="<?php echo $idCamposModal[6]?>" id="<?php echo $idCamposModal[6]?>-idioma"><?php echo $idCamposTitleModal[5]?></label></td>
                                    <td><select class="input-small" name="<?php echo $idCamposModal[6]?>" id="<?php echo $idCamposModal[6]?>" style="width:150px;" ><option value="-1">---Seleccione---</option></select></td>

                                    <td><label  for="arbollabel_modal" id="<?php echo $idCamposModal[5]?>-idioma" style="font: bold;color:#000000 ;padding:5px;"><?php echo $idCamposTitleModal[4]?></label></td>
                                    <td><fieldset style="font: bold;background:#49AFCD;color:white"><input type="radio" name="group1" id="<?php echo $idCamposModal[5]?>-si">S&iacute<br>
                                    <input type="radio" name="group1" checked value="SEPARADO" id="<?php echo $idCamposModal[5]?>-no">No</fieldset></td>                                    
                                </tr>
                            </table>
                        </div>
<!-- 
######################################   CAMPOS DEL DETALLE    ######################################################################################
-->
                        <div id="contenedorDetalles-modal" >
                            <div id="detallesModal-idioma" class="btn btn-info" >
                                <h3 id="detallesModal-nuevo">Detalles</h3>
                            </div><br><br>                            
                            <table>
                                <tr>
                                    <td><label for="<?php echo $idCamposModal[7]?>" id="<?php echo $idCamposModal[7]?>-idioma"><?php echo $idCamposTitleModal[6]?></label></td>
                                    <td><select class="input-small" name="<?php echo $idCamposModal[7]?>" id="<?php echo $idCamposModal[7]?>" style="width:150px;" onchange="cargarDatosInsumo();"><option value="-1">---Seleccione---</option></select></td>
                                    
                                    <td><label for="<?php echo $idCamposModal[8]?>" id="<?php echo $idCamposModal[8].'-idioma'?>"><?php echo $idCamposTitleModal[7] ?><font style="color: red;">(*)</font></label></td>
                                    <td><input id="<?php echo $idCamposModal[8]?>" maxlength="45" style="width:150px;" onkeypress='return validarNumerosLetrasPorcentageEspacio(event);' ></input></td>
                                    
                                    <td><b>&nbsp;</b></td>
                                    <td><label for="<?php echo $idCamposModal[11]?>" id="<?php echo $idCamposModal[11]?>"></label></td>
                                    <input type="hidden" id="idImpuestoInsumo" name="idImpuestoInsumo">
                                    <input type="hidden" id="idImpuestoPorcentaje" name="idImpuestoPorcentaje">
                                    
                                    <td><label for="<?php echo $idCamposModal[9]?>" id="<?php echo $idCamposModal[9].'-idioma'?>"><?php echo $idCamposTitleModal[8] ?><font style="color: red;">(*)</font></label></td>
                                    <td><input id="<?php echo $idCamposModal[9]?>" maxlength="45" style="width:150px;" onkeypress='return validarNumerosLetrasPorcentageEspacio(event);' ></input></td>                                    
                                                                                                           
                                    <td><label for="<?php echo $idCamposModal[10]?>" id="<?php echo $idCamposModal[10]?>"></label></td>                                    
                                    <td><a id="addDetalleRegistro"  class="btn btn-info"><img src="<?= $this->baseUrl() . "/css/images/add.png"; ?>" id="addDetalleBtn" title="Add Detalle"  width="18px" style="cursor: hand;"/></a></td>

                                </tr>
                            </table>
                                    
                            <div id="detallesDiv" title="Clientes" class="hide">
                                    <table id="grilla" class="lista" width="700px">
                                        <thead>
                                            <tr class="encabezado">
                                                <td><b>Insumo</b></td>                                                
                                                <td><b>Cantidad Compra</b></td>
                                                <td><b>Impuesto Compra</b></td>
                                                <td><b>Monto Compra</b></td>
                                                <td><b>&nbsp;</b></td>
                                            </tr>
                                        </thead>
                                        <tbody id="tbodyGrillaDetalles">
                                        </tbody>        
                                    </table>
                                    <table id="grillaTotales" class="lista" width="700px">
                                        <thead>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td><b>&nbsp;</b></td>      
                                                <td><b>Total Compra : </b></td>
                                                <td><div id="totalCompra" align="left">0</div></td>
                                                <td><b>Total Impuesto : </b></td>
                                                <td><div id="totalImpuesto" align="left">0</div></td>                                                
                                                <td><b>&nbsp;</b></td>      
                                            </tr>                                                    
                                        </tbody>        
                                    </table>                
                            </div>                                    
                                    
                        </div>                        
<!-- 
##############################################################################################################################
-->                        
                        <div id="contenedor-modal">
                            <strong><font style="color: red;">(*)</font> Complete los campos marcados en el formulario para guardar el Registro</strong>
                        </div>
                    </div>

                    <div class="modal-footer">
                        <a data-dismiss="modal" class="btn" href="#" id="cancelar-bot">Cancelar</a>
                        <a class="btn btn-info" id="guardar-registro" href="#">Guardar</a>
                    </div>
                </div>

                <div class="container-fluid">
                    <div class="row-fluid">
                        <div class="span10" id="span10">
                            <br>
                                <div id="cabeceraFormulario" class="btn btn-info" >
                                    <h1 id="cabecera-titulo" align="center" ><?php echo $titulo ?></h1>

                                    <div class="alert alert-block hide" id="warning-block-registro-listado">
                                        <div id="warning-message-registro-listado"></div>
                                    </div>

                                    <div class="alert alert-success hide" id="success-block-registro-listado">
                                        <div id="success-message-registro-listado"></div>
                                    </div>

                                    <div class="alert alert-error hide" id="error-block-registro-listado">
                                    </div>

                                    <div class="alert alert-info hide" id="info-block-listado">
                                        <div id="info-message"></div>
                                    </div>



                                </div>
                                <div  id="clientes-div">
                                    <div id="contenedor" >
                                        <fieldset>
                                            <table border="0">
                                                <tr>                                                    
                                                    <td><label for="<?php echo $idCamposBusqueda[0]?>" id="<?php echo $idCamposBusqueda[0]?>-idioma"><?php echo $idCamposTitleBusqueda[0]?></label></td>
                                                    <td><select class="input-small" name="<?php echo $idCamposBusqueda[0]?>" id="<?php echo $idCamposBusqueda[0]?>" style="width:150px;" ><option value="-1">---Seleccione---</option></select></td>
                                                    <td><label for="<?php echo $idCamposBusqueda[1]?>" id="<?php echo $idCamposBusqueda[1]?>-idioma"><?php echo $idCamposTitleBusqueda[1]?></label></td>
                                                    <td><select class="input-small" name="<?php echo $idCamposBusqueda[1]?>" id="<?php echo $idCamposBusqueda[1]?>" style="width:150px;" ><option value="-1">---Seleccione---</option></select></td>
                                                    <td><label for="<?php echo $idCamposBusqueda[2]?>" id="<?php echo $idCamposBusqueda[2]?>-idioma"><?php echo $idCamposTitleBusqueda[2]?></label></td>
                                                    <td><input id="<?php echo $idCamposBusqueda[2]?>" maxlength="50"  onkeypress='return validarNumerosLetrasPorcentageEspacio(event);'></input></td>
                                                </tr>
                                            </table>
                                        </fieldset>

                                    </div>
                                </div>
                                <div  id="tab-content">
                                    <div id="contenedor" >
                                        <a id="buscarregistro"  class="btn btn-info"><img src="<?= $this->baseUrl() . "/css/images/buscar.png"; ?>" id="buscar-img" title="Buscar"  style="cursor: hand;"/></a>
                                        <a id="nuevoregistro"  class="btn btn-info"  data-toggle="modal"><img src="<?= $this->baseUrl() . "/css/images/nuevo.png"; ?>" id="nuevo-img" title="Nuevo"  style="cursor: hand;"/></a>
                                    </div>
                                </div>
                                <div id="contenedor" >
                                    <fieldset>
                                        <table border="0">
                                            <tr>
                                                <td>
                                                    <div class="tab-content" id="tab-content">
                                                        <!-- DATOS DE IMPUESTOS --->
                                                        <div id="grillaPaginadorRegistro">
                                                            <table id="grillaRegistro"></table>
                                                            <div id="paginadorRegistro"></div>
                                                        </div>

                                                    </div>
                                                </td>
                                            </tr>
                                        </table>
                                    </fieldset>
                                </div>

                        </div>
                    </div>
                </div>
            </CENTER>
        </body>
    </html>