<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//ES" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <?php
    echo $this->headScript()->
            appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
            appendFile($this->baseUrl() . "/js/jquery-ui-1.8.17.custom.min.js")->
            appendFile($this->baseUrl() . '/js/i18n/grid.locale-es.js')->
            appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
            appendFile($this->baseUrl() . "/js/bootstrap.js")->
            appendFile($this->baseUrl() . "/js/jsmodulos/produccion/BajaStock.js")->
            appendFile($this->baseUrl() . "/js/grillasmodulos/produccion/gridBajaStock.js")->
            appendFile($this->baseUrl() . "/js/jquery.tablescroll.js")->
            appendFile($this->baseUrl() . "/js/jquery.blockUI.js");

    echo $this->headLink()
            ->setIndent('  ')
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/generico.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.datepicker.css")
            ->prependStylesheet($this->baseUrl() . "/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/jquery-ui-1.8.17.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap-responsive.css")
   			->prependStylesheet($this->baseUrl() . "/css/cssgenerico/contenedor.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/CssGeneral.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/default.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/parametricos/menucss3/css/cool_nav.css")
    ?>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Infocomedor</title>
    </head>
    <body>
             
        <div class="container-fluid"> 

            <div class="row-fluid">
                <div class="span10">
                    <div  class="titulo-cabecera" style="text-align: left">
                       <nav id="colorNav" >
                        <ul>
                            <li class="menu">
                                <a href="<?php echo $this->baseUrl() ."/parametricos/menu";?>" class="">MENU</a>
                           </li>
                            <li class="red">
                                <a href="#" class="" title="COMPRAS">COMPRAS</a>
                                <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/proveedor";?>">Proveedor</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/compra2";?>">Compras - Pagos</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/pagos";?>">Pagos</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/Reportecompras";?>">Reporte Compras</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/Reportepagos";?>">Reporte Pagos</a></li>

                              
                            </ul>
                            </li>
                            <li class="green">
                                <a href="#" class="" title="PRODUCCION">PRODUCCION</a>
                                <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/tipoproducto";?>">Tipo Producto</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/producto";?>">Producto</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/produccion/receta";?>">Recetas</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/produccion/productofinal";?>">Produccion</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/produccion/Reporteproduccion";?>"> Reporte Produccion</a></li>

                            </ul>
                            </li>
                            <li class="blue">
                                <a href="#" class="" title="VENTAS">VENTAS</a>
                                <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/empresa";?>">Empresa Clientes</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/parametricos/cliente";?>">Clientes</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/karrito";?>">Pedidos</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/factura";?>">Facturación</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/Reporteclientes";?>">Reporte Clientes</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/Reportefacturacion";?>">Reporte Facturación</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/Reportepedidos";?>">Reporte Pedidos</a></li>
                                
                            </ul>
                            </li>
                            <li class="yellow">
                                <a href="#" class="" title="INVENTARIO">INVENTARIO</a>
                                <ul>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/inventario";?>">Inventario</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/ajusteinventario";?>">Ajuste</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/bajastock";?>">Baja Stock</a></li>
                                </ul>
                            </li>
                            <li class="purple">
                                <a href="#" class=""title="CAJA">CAJA</a>
                               <ul>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/caja";?>">Caja</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/tipomovimiento";?>">Tipo Movimiento</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/movcaja";?>">Movimientos</a></li>
                                   <li><a href="<?php echo $this->baseUrl() ."/caja/Reportearqueocaja";?>">Reporte Arqueo de caja</a></li>
                                </ul>
                           </li>
                           <li class="">
                                <a href="<?php echo $this->baseUrl() ."/menus/menu";?>">LogOut</a>
                           </li>

                        </ul>
                    </nav>
	            </div> 
                    <div  class="titulo-cabecera">
                        <h1 id="cabecera-titulo">Baja de Stock</h1>

                    </div>
                    
                    <div>
                        <div class="alert alert-block hide" id="warning-block-title">
                            <div id="warning-message-title"></div>
                        </div>
                        <div class="alert alert-success hide" id="success-block-title">
                            <div id="success-message-title"></div>
                        </div>
                        <div class="alert alert-info hide" id="info-block-listado">
                            <div id="info-message"></div>
                        </div>
                        <div id="contenedor" class="filtro" align=center>
                            <table style="width: 90%; padding: 1%;">
                                <tr>
                                   <td style="width: 25%; text-align: right">
                                        <label for="descripciontipoproducto-filtro" id="descripciontipoproducto-filtro-idioma">Descripción </label>
                                    </td>
                                    <td style="width: 40%">
                                        <input id="descripciontipoproducto-filtro"  class="input-block-level" >
                                    </td>
                                    
                                </tr>
                            </table>
                           
                        </div>
                        <div  id="tab-content">
                            <div id="contenedor" align=center>
                               
                                <a id="buscarregistro"  class="btn btn-info"><img src="<?php echo $this->baseUrl() . "/css/images/buscar.png"; ?>" id="buscar-img" title="Buscar"  style="cursor: hand;"/></a>
                                <a id="nuevoregistro"  class="btn btn-info" <?php echo $this->guardar ?>><img src="<?php echo $this->baseUrl() . "/css/images/nuevo.png"; ?>" id="nuevo-img" title="Baja Stock"  style="cursor: hand;"/></a>
                            </div> 
                        </div>
                    </div>
                    <div id="contenedor" >
                        <div class="contenedor-grid">
                            <table id="grillaRegistro"></table>
                            <div id="paginadorRegistro"></div>
                        </div>
                    </div>
                </div>


                <div class="modal hide" id="modalEditar">
                    <div class="modal-header">

                        <div id="cabeceraModal" class="btn btn-info">
                            <h3 id="editar-nuevo" style="color:white; display: inline;"><?php echo 'Baja Stock'; ?></h3>
                            <button data-dismiss="modal" class="close" type="button" id="cerrar-bot" style="display: inline">x</button>
                        </div>
                        <div class="alert alert-block hide" id="warning-block">
                            <div id="warning-message"></div>
                        </div>
                        <div class="alert alert-success hide" id="success-block"><?php echo 'Datos Almacenados Exitosamente'; ?></div>
                        <div class="alert alert-error hide" id="error-block"></div>
                        <div class="alert alert-success hide" id="limpiar-block"></div>
                    </div>
                    <!-- NUEVO - EDITAR --->
                    <div class="modal-body">
                        <div id="contenedor-modal"> <!--style="/*width: 100%;*/width:750px; padding:5px 0;border: 2px solid #C6E9FF;border-color: #BCE8F1;background: #D9EDF7;"-->
                            <table class=" form-inline">
                                <!-- AGREGAR CAMPOS AQUI-->
                                <tr>
                                    <input type="hidden" id="cod_baja_stock-hidden"></input>
                                    <input type="hidden" id="codunidadproducto-hidden"></input>                                    
                                    <td><label for="productostock-label" id="productostock-idioma">Producto</label></td>
                                    <td><select class="input-small" name="productostock-select" id="productostock-select" style="width:150px;" onchange="buscarUnidadMedida();" ><option value="-1">---Seleccione---</option></select></td>                                                                                                                
                                    <td style="width: 16%">
                                        <label for="unidadproducto-label" id="unidadproducto-label">Unidad de Medida</label>
                                    </td> 
                                    <td style="width: 16%">
                                        <input readonly="" id="unidadproducto-input" maxlength="45" class="unidadproducto-input"></input>
                                    </td> 
                                    <td style="width: 16%">
                                        <label for="cantidadactual-label" id="cantidadactual-label">Cantidad Actual</label>
                                    </td> 
                                    <td style="width: 16%">
                                        <input readonly="" id="cantidadactual-input" maxlength="45" class="just-number" onkeypress='' value=''></input>
                                    </td>                                                                          
                                </tr>
                                <tr>
                                    <td style="width: 16%">
                                        <label for="cantidadbaja-label" id="cantidadbaja-label">Cantidad Baja</label>
                                    </td> 
                                    <td style="width: 16%">
                                        <input  id="cantidadbaja-input" maxlength="45" class="just-number" onkeypress='' value=''></input>
                                    </td>   
                                    <td style="width: 16%">
                                        <label for="observacionbaja-label" id="observacionbaja-label">Observacion Baja</label>
                                    </td> 
                                    <td style="width: 16%">
                                        <input  id="observacionbaja-input" maxlength="99" class="" onkeypress='' value=''></input>
                                    </td>                                     
                                </tr>
                                <tr>
                                    <td style="width: 16%">
                                        <label for="montoentrantecaja-modal" id="montoentrantecaja-modal-idioma">Total de Ingresos Caja</label>
                                    </td> 
                                    <td style="width: 16%">
                                        <input id="montoentrantecaja-modal" maxlength="45" class="input-block-level" onkeypress=''></input>
                                    </td> 									
                                    <td style="width: 16%">
                                        <label for="montosalientecaja-modal" id="montosalientecaja-modal-idioma">Total de Egresos Caja</label>
                                    </td> 
                                    <td style="width: 16%">
                                        <input id="montosalientecaja-modal" maxlength="45" class="input-block-level" onkeypress=''></input>
                                    </td> 									                                    
                                </tr>                                
<!--                                
                                <tr>
                                    <td>
                                        <label for="usuariocaja-modal" id="usuariocaja-modal-idioma">Usuario</label>                                        
                                    </td>
                                    <td>                                        
                                        <select class="input-block-level" name="usuariocaja-modal-idioma" id="usuariocaja-modal" onchange="">
                                            <option value="-1">Seleccione</option>
                                        </select>
                                    </td>    
                                </tr>  
-->                                
                            </table>                            
                        </div>
                    </div>
                        
                       
                    <div class="modal-footer">
                        <a data-dismiss="modal" class="btn" id="cancelar-bot"><?php echo 'Cancelar'; ?></a>
                        <a class="btn btn-info" id="guardar"><?php echo 'Guardar'; ?></a>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>