<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//ES" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <?php
	
	$titulo = "Proveedores";
    $labelDescripcion = "Descripci&oacuten del Proveedor";
    $labelsGrillas = array('Descripci&oacute;n del Proveedor', 'Ruc', 'Direcci&oacuten', 'Tel&eacutefono', 'Contacto', 'Email', 'Limite Cr&eacutedito');
	 $idCamposGrilla = array("id-registro", "descripcionBusqueda-modal", "ruc-modal", "direccion-modal", "telefono-modal", "nombrecontacto-modal", "email-modal", "limitecredito-modal");
    echo $this->headScript()->
            appendFile($this->baseUrl() . "/js/jquery-1.7.1.js")->
            appendFile($this->baseUrl() . "/js/jquery-ui-1.8.17.custom.min.js")->
            appendFile($this->baseUrl() . '/js/i18n/grid.locale-es.js')->
            appendFile($this->baseUrl() . '/js/jquery.jqGrid.min.js')->
            appendFile($this->baseUrl() . "/js/bootstrap.js")->
            appendFile($this->baseUrl() . "/js/jsmodulos/parametricos/Proveedor.js")->
            appendFile($this->baseUrl() . "/js/grillasmodulos/parametricos/gridProveedor.js")->
            appendFile($this->baseUrl() . "/js/jquery.tablescroll.js")->
            appendFile($this->baseUrl() . "/js/jquery.blockUI.js");

    echo $this->headLink()
            ->setIndent('  ')
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/generico.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.datepicker.css")
            ->prependStylesheet($this->baseUrl() . "/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/jquery-ui-1.8.17.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap-responsive.css")
   			->prependStylesheet($this->baseUrl() . "/css/cssgenerico/contenedor.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/CssGeneral.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/default.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/parametricos/menucss3/css/cool_nav.css")
    ?>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Infocomedor</title>
    </head>
    <body>
             
        <div class="container-fluid"> 

            <div class="row-fluid">
                <div class="span10">
	                   <div  class="titulo-cabecera" style="text-align: left">
                     <nav id="colorNav" >
                        <ul>
                            <li class="menu">
                                <a href="<?php echo $this->baseUrl() ."/parametricos/menu";?>" class="">MENU</a>
                           </li>
                            <li class="red">
                                <a href="#" class="" title="COMPRAS">COMPRAS</a>
                                <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/proveedor";?>">Proveedor</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/compra2";?>">Compras - Pagos</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/pagos";?>">Pagos</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/Reportecompras";?>">Reporte Compras</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/Reportepagos";?>">Reporte Pagos</a></li>

                              
                            </ul>
                            </li>
                            <li class="green">
                                <a href="#" class="" title="PRODUCCION">PRODUCCION</a>
                                <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/tipoproducto";?>">Tipo Producto</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/producto";?>">Producto</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/produccion/receta";?>">Recetas</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/produccion/productofinal";?>">Produccion</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/produccion/Reporteproduccion";?>"> Reporte Produccion</a></li>

                            </ul>
                            </li>
                            <li class="blue">
                                <a href="#" class="" title="VENTAS">VENTAS</a>
                                <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/empresa";?>">Empresa Clientes</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/parametricos/cliente";?>">Clientes</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/karrito";?>">Pedidos</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/factura";?>">Facturación</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/Reporteclientes";?>">Reporte Clientes</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/Reportefacturacion";?>">Reporte Facturación</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/Reportepedidos";?>">Reporte Pedidos</a></li>
                                
                            </ul>
                            </li>
                            <li class="yellow">
                                <a href="#" class="" title="INVENTARIO">INVENTARIO</a>
                                <ul>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/inventario";?>">Inventario</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/ajusteinventario";?>">Ajuste</a></li>
                                     <li><a href="<?php echo $this->baseUrl() ."/produccion/bajastock";?>">Baja Stock</a></li>
                                </ul>
                            </li>
                            <li class="purple">
                                <a href="#" class=""title="CAJA">CAJA</a>
                               <ul>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/caja";?>">Caja</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/tipomovimiento";?>">Tipo Movimiento</a></li>
                                    <li><a href="<?php echo $this->baseUrl() ."/caja/movcaja";?>">Movimientos</a></li>
                                   <li><a href="<?php echo $this->baseUrl() ."/caja/Reportearqueocaja";?>">Reporte Arqueo de caja</a></li>
                                </ul>
                           </li>
                           <li class="">
                                <a href="<?php echo $this->baseUrl() ."/menus/menu";?>">LogOut</a>
                           </li>

                        </ul>
                    </nav>                     
	                </div> 
                    <div  class="titulo-cabecera">
                        <h1 id="cabecera-titulo">Proveedor</h1>

                    </div>

                    <div>
                        <div class="alert alert-block hide" id="warning-block-title">
                            <div id="warning-message-title"></div>
                        </div>
                        <div class="alert alert-success hide" id="success-block-title">
                            <div id="success-message-title"></div>
                        </div>
                        <div class="alert alert-info hide" id="info-block-listado">
                            <div id="info-message"></div>
                        </div>
                        <div id="contenedor" class="filtro" align=center>
                            <table style="width: 90%; padding: 1%;">
                                <tr>
                                   <td style="width: 25%; text-align: right">
                                        <label for="descripcionBusqueda"  id="descripcionBusqueda-idioma"><?php echo $labelDescripcion ?></label>
                                    </td>
                                    <td style="width: 40%">
										<input id="descripcionBusqueda" class="input-block-level" maxlength="50" onkeypress='return validarNumerosLetrasPorcentageEspacio(event);'></input>
                                    </td>
                                    
                                </tr>
                            </table>
                           
                        </div>
                        <div  id="tab-content">
                            <div id="contenedor" align=center>
                                
                                <a id="buscarregistro"  class="btn btn-info"><img src="<?= $this->baseUrl() . "/css/images/buscar.png"; ?>" id="buscar-img" title="Buscar"  style="cursor: hand;"/></a>
                                <a id="nuevoregistro"  class="btn btn-info"  data-toggle="modal"><img src="<?= $this->baseUrl() . "/css/images/nuevo.png"; ?>" id="nuevo-img" title="Nuevo"  style="cursor: hand;"/></a>
                            </div> 
                        </div>
                    </div>
                    <div id="contenedor" >
<!--                        <div class="contenedor-grid">-->
                            <table id="grillaRegistro"></table>
                            <div id="paginadorRegistro"></div>
<!--                        </div>-->
                    </div>
                </div>


                <div class="modal hide" id="modalEditar">
                     <div class="modal-header">
                        <button data-dismiss="modal" class="close" type="button" id="cerrar-bot">X</button>
                        <div id="cabeceraModal" class="btn btn-info" >
                            <h3 id="editar-nuevo" ></h3>
                        </div>

                        <div class="alert alert-block hide" id="warning-block-registro">
                            <div id="warning-message-registro"></div>
                        </div>
                        <div class="alert alert-success hide" id="success-block-registro">
                            Los datos han sido almacenados exitosamente
                        </div>
                        <div class="alert alert-error hide" id="error-block-modal">
                        </div>
                        <div class="alert alert-success hide" id="limpiar-block"></div>


                    </div>
    
                    <div class="modal-body">
                        <div id="contenedor-modal"> 
                            <table class=" form-inline">
                                <!-- AGREGAR CAMPOS AQUI-->
                                <input type="hidden" id="<?php echo $idCamposGrilla[0] ?>"></input>
                                <tr>
                                    <td><label for="<?php echo $idCamposGrilla[1] ?>" id="<?php echo $idCamposGrilla[1] . '-idioma' ?>">
                                        <?php echo $labelsGrillas[0] ?></label>
                                        <input id="<?php echo $idCamposGrilla[1] ?>" class="input-block-level" maxlength="45" onkeypress='return validarNumerosLetrasPorcentageEspacio(event);' ></input>
                                    </td>
                                
                                    <td><label for="<?php echo $idCamposGrilla[2] ?>" id="<?php echo $idCamposGrilla[2] . '-idioma' ?>">
                                        <?php echo $labelsGrillas[1] ?> </label>
                                        <input id="<?php echo $idCamposGrilla[2] ?>" maxlength="45" class="input-block-level" onkeypress='return validarNumerosLetrasPorcentageEspacio(event);' ></input></td>
                                
                                    <td><label for="<?php echo $idCamposGrilla[3] ?>" id="<?php echo $idCamposGrilla[3] . '-idioma' ?>"><?php echo $labelsGrillas[2] ?> </label>
                                        <input id="<?php echo $idCamposGrilla[3] ?>" maxlength="45" class="input-block-level" onkeypress='return validarNumerosLetrasPorcentageEspacio(event);' ></input></td>
                               
                                    <td><label for="<?php echo $idCamposGrilla[4] ?>" id="<?php echo $idCamposGrilla[4] . '-idioma' ?>"><?php echo $labelsGrillas[3] ?> </label>
                                        <input id="<?php echo $idCamposGrilla[4] ?>" maxlength="45" class="input-block-level" onkeypress='return validarNumerosLetrasPorcentageEspacio(event);' ></input></td>
                                 </tr>
                                <tr>

                                
                                    <td><label for="<?php echo $idCamposGrilla[5] ?>" id="<?php echo $idCamposGrilla[5] . '-idioma' ?>"><?php echo $labelsGrillas[4] ?> </label>
                                        <input id="<?php echo $idCamposGrilla[5] ?>" maxlength="45" class="input-block-level" onkeypress='return validarNumerosLetrasPorcentageEspacio(event);' ></input></td>
                                
                                    <td><label for="<?php echo $idCamposGrilla[6] ?>" id="<?php echo $idCamposGrilla[6] . '-idioma' ?>"><?php echo $labelsGrillas[5] ?> </label>
                                        <input id="<?php echo $idCamposGrilla[6] ?>" maxlength="45" class="input-block-level" ></input></td>
                                
                                    <td><label for="<?php echo $idCamposGrilla[7] ?>" id="<?php echo $idCamposGrilla[7] . '-idioma' ?>"><?php echo $labelsGrillas[6] ?> </label>
                                        <input id="<?php echo $idCamposGrilla[7] ?>" maxlength="12" class="input-block-level" onkeypress='return validarNro(event);'  ></input></td>
                                </tr>
                                
                            </table>
                        </div>
                    </div>
                        
                       
                    <div class="modal-footer">
                            <a data-dismiss="modal" class="btn" href="#" id="cancelar-bot">Cancelar</a>
                        <a class="btn btn-info" id="guardar-registro" href="#">Guardar</a>
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>