<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//ES" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
    <?php
    echo $this->headLink()
            ->setIndent('  ')
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.datepicker.css")
            ->prependStylesheet($this->baseUrl() . "/jquery-ui-1.10.3.custom/css/ui-lightness/jquery-ui-1.10.3.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/jquery-ui-1.8.17.custom.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/bootstrap-responsive.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/contenedor.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssgenerico/ui.jqgrid.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/parametricos/menucss3/font-awesome/css/font-awesome.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/parametricos/menucss3/css/main.css")
            ->prependStylesheet($this->baseUrl() . "/css/cssmodulos/parametricos/menucss3/css/cool_nav.css")
    ?>

    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
        <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Infocomedor</title>
    </head>
    <body>
        <!-- BestOfjQueryPlugins main section -->

        <div class="ivan">
            <div style="margin-top: 10%;">
                <h1>INFOCOMEDOR</h1>
                <br><br>
                
                <nav id="colorNav" >
                    <ul>
                        
                        <li class="red">
                            <a href="#" class="icon-shopping-cart" title="COMPRAS"></a>
                            <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/proveedor";?>">Proveedor</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/compra2";?>">Compras - Pagos</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/pagos";?>">Pagos</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/Reportecompras";?>">Reporte Compras</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/compras/Reportepagos";?>">Reporte Pagos</a></li>

                              
                            </ul>
                        </li>
                        <li class="green">
                            <a href="#" class="icon-glass" title="PRODUCCION"></a>
                            <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/tipoproducto";?>">Tipo Producto</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/producto";?>">Producto</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/produccion/receta";?>">Recetas</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/produccion/productofinal";?>">Produccion</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/produccion/Reporteproduccion";?>"> Reporte Produccion</a></li>

                            </ul>
                        </li>
                        <li class="blue">
<!--                            <a href="#" class="icon-twitter"></a>-->
                            <a href="#" class="icon-edit" title="VENTAS"></a>
                            <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/empresa";?>">Empresa Clientes</a></li>
                            	 <li><a href="<?php echo $this->baseUrl() ."/parametricos/cliente";?>">Clientes</a></li>
                            	 <li><a href="<?php echo $this->baseUrl() ."/ventas/karrito";?>">Pedidos</a></li>
				                 <li><a href="<?php echo $this->baseUrl() ."/ventas/factura";?>">Facturación</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/Reporteclientes";?>">Reporte Clientes</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/Reportefacturacion";?>">Reporte Facturación</a></li>
                                 <li><a href="<?php echo $this->baseUrl() ."/ventas/Reportepedidos";?>">Reporte Pedidos</a></li>
                                
                            </ul>
                        </li>
                        <li class="yellow">
                            <a href="#" class="icon-print" title="INVENTARIO"></a>
                            <ul>
                            <li><a href="<?php echo $this->baseUrl() ."/produccion/inventario";?>">Inventario</a></li>
                            <li><a href="<?php echo $this->baseUrl() ."/produccion/ajusteinventario";?>">Ajustes</a></li>
                            <li><a href="<?php echo $this->baseUrl() ."/produccion/bajastock";?>">Baja Stock</a></li>
                          
                              </ul>
                        </li>
                        <li class="purple">
                            <a href="#" class="icon-envelope"></a>
                           <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/caja/caja";?>">Caja</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/caja/tipomovimiento";?>">Tipo Movimiento</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/caja/movcaja";?>">Movimientos</a></li>
                               <li><a href="<?php echo $this->baseUrl() ."/caja/Reportearqueocaja";?>">Reporte Arqueo de caja</a></li>
                           </ul>
                       </li>
                       <li class="menu">
                            <a href="" class="icon-user">
                            </a>
                            <ul>
                                <li><a href="<?php echo $this->baseUrl() ."/menus/menu";?>">LogIn</a></li>
                                <li><a href="<?php echo $this->baseUrl() ."/parametricos/usuario";?>">Usuarios</a></li>
                           </ul>
                       </li>
                    </ul>
                </nav>
            </div>

            <!-- /BestOfjQueryPlugins main section -->
        </div>
    </div>
</body>
</html>    


</html>